### ISSUE TITLE
Extensions do not work as advertised.

### ISSUE THREAD

**Issue by ChrisGWarp** [PeterMosmans/ansible-role-customize-gnome#8]
The README doco states:

`The properties url and/or name of each item can also be loaded dynamically from the web when id is present. Predefined name and/or url will not be overridden! Here is an example that loads the same extension as the example above.

gnome_extensions:
  - id: 545`

However, when I use only an id field, the role fails with an undefined variable. The error is:
`fatal: [X.X.X.X]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to be in '/home/dev-user/.ansible/roles/PeterMosmans.customize-gnome/tasks/main.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download GNOME Shell extensions\n  ^ here\n"}`

It is failing here, because the list is not empty (as an id is supplied), and fails because there is no URL or NAME supplied:

`- name: Download GNOME Shell extensions`
`  get_url:`
`    url: "{{ item.url }}"`
`    dest: "/tmp/{{ item.name }}.zip"`
`  with_items: "{{ gnome_extensions|default([]) }}"`
`  tags:`
`    - extensions`

Moreover, I can't see how it ever worked.

This is what I am supplying:

`    - role: PeterMosmans.customize-gnome`
`      vars:`
`        gnome_user: dev-user`
`        gnome_extensions:`
`          - id: 1160`

**Comment by PeterMosmans** [comment]
Hi @ChrisGWarp - thanks for the report. The extensions variable is a list key value pairs, which need to at least contain a **url** as well as **name** value:
```
gnome_extensions:
  - url: "https://extensions.gnome.org/download-extension/hidetopbar@mathieu.bidon.ca.shell-extension.zip?version_tag=6450"
    name: "hidetopbar@mathieu.bidon.ca"
```

Isn't the README clear on that? Right now it states:

"**gnome_extensions**: A list of GNOME shell extensions that will be
downloaded from a remote source and unzipped to the users' local extensions
directory. Each list item consists of an `url` and `name`."

**Comment by ctorgalson** [comment]
Hi @PeterMosmans,

Thanks for this role--I was on the point of creating one like it :)

Anyway, I think the issue is the the README is slightly contradictory. Along with what you quoted [there's this](https://github.com/PeterMosmans/ansible-role-customize-gnome/blob/master/README.md?plain=1#L63-L67) (emphasis added), as well as [`tasks/get_extension_info.yml`](https://github.com/PeterMosmans/ansible-role-customize-gnome/blob/master/tasks/get_extension_info.yml#L7) that only runs if one or both of `name` and `url` are absent:

> **The properties `url` and/or `name` of each item can also be loaded dynamically from [the web](https://extensions.gnome.org/extension-info/?pk=545) when `id` is present**. Predefined `name` and/or `url` will not be overridden! Here is an example that loads the same extension as the example above.
>
> ```
> gnome_extensions:
>   - id: 545
> ``` 

As for this issue, [`tasks/get_extension_info.yml`](https://github.com/PeterMosmans/ansible-role-customize-gnome/blob/master/tasks/get_extension_info.yml), if the role fails when only an `id` is provided, then the issue probably lies here, [where `r_gnome_extension_info`](https://github.com/PeterMosmans/ansible-role-customize-gnome/blob/master/tasks/get_extension_info.yml#L6) is registered (afaict, the following task should work if the json response is correctly structured).

I'll be testing the role this afternoon, so if I can reproduce this issue I'll see if I can discover the cause. If I can't, I'll update this issue as well.

**Comment by ctorgalson** [comment]
> I'll be testing the role this afternoon, so if I can reproduce this issue

I do see the same issue.
